/* 
 * Brainrex API Explorer
 *
 * Welcome to the Brainrex API explorer, we make analytics tools for crypto and blockchain. Our currently propiertary models offer sentiment analysis, market making, blockchain monitoring and face-id verification. This AI models can be consumed from this API. We also offer integrations to open data and propietary data providers, as well as free test data we collect. There is a collection of data transformation tools. Join our Telegram group to get the latest news and ask questions [https://t.me/brainrex, #brainrex](https://t.me/brainrex). More about Brainrex at [https://brainrex.com](http://brainrex.com). Full Documentation can be found at [https://brainrexapi.github.io/docs](https://brainrexapi.github.io/docs)
 *
 * OpenAPI spec version: 0.1.1
 * Contact: support@brainrex.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISentimentAnalysisApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Sentiment analysis score using a model trained for buy signals.
        /// </summary>
        /// <remarks>
        /// Gives a 0 to 1 score, depending on buy/sell sentiment
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>string</returns>
        string SentimentGetPriceSentiment (Text1 text);

        /// <summary>
        /// Sentiment analysis score using a model trained for buy signals.
        /// </summary>
        /// <remarks>
        /// Gives a 0 to 1 score, depending on buy/sell sentiment
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> SentimentGetPriceSentimentWithHttpInfo (Text1 text);
        /// <summary>
        /// Sentiment analysis for any given blob of text
        /// </summary>
        /// <remarks>
        /// Gives a -1 to 1 score, depending on bearish/bullish sentiment
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>string</returns>
        string SentimentGetSentiment (Text text);

        /// <summary>
        /// Sentiment analysis for any given blob of text
        /// </summary>
        /// <remarks>
        /// Gives a -1 to 1 score, depending on bearish/bullish sentiment
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> SentimentGetSentimentWithHttpInfo (Text text);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Sentiment analysis score using a model trained for buy signals.
        /// </summary>
        /// <remarks>
        /// Gives a 0 to 1 score, depending on buy/sell sentiment
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> SentimentGetPriceSentimentAsync (Text1 text);

        /// <summary>
        /// Sentiment analysis score using a model trained for buy signals.
        /// </summary>
        /// <remarks>
        /// Gives a 0 to 1 score, depending on buy/sell sentiment
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> SentimentGetPriceSentimentAsyncWithHttpInfo (Text1 text);
        /// <summary>
        /// Sentiment analysis for any given blob of text
        /// </summary>
        /// <remarks>
        /// Gives a -1 to 1 score, depending on bearish/bullish sentiment
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> SentimentGetSentimentAsync (Text text);

        /// <summary>
        /// Sentiment analysis for any given blob of text
        /// </summary>
        /// <remarks>
        /// Gives a -1 to 1 score, depending on bearish/bullish sentiment
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> SentimentGetSentimentAsyncWithHttpInfo (Text text);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SentimentAnalysisApi : ISentimentAnalysisApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SentimentAnalysisApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SentimentAnalysisApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SentimentAnalysisApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SentimentAnalysisApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Sentiment analysis score using a model trained for buy signals. Gives a 0 to 1 score, depending on buy/sell sentiment
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>string</returns>
        public string SentimentGetPriceSentiment (Text1 text)
        {
             ApiResponse<string> localVarResponse = SentimentGetPriceSentimentWithHttpInfo(text);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Sentiment analysis score using a model trained for buy signals. Gives a 0 to 1 score, depending on buy/sell sentiment
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > SentimentGetPriceSentimentWithHttpInfo (Text1 text)
        {
            // verify the required parameter 'text' is set
            if (text == null)
                throw new ApiException(400, "Missing required parameter 'text' when calling SentimentAnalysisApi->SentimentGetPriceSentiment");

            var localVarPath = "/get_buy_sentiment";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (text != null && text.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(text); // http body (model) parameter
            }
            else
            {
                localVarPostBody = text; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SentimentGetPriceSentiment", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Sentiment analysis score using a model trained for buy signals. Gives a 0 to 1 score, depending on buy/sell sentiment
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> SentimentGetPriceSentimentAsync (Text1 text)
        {
             ApiResponse<string> localVarResponse = await SentimentGetPriceSentimentAsyncWithHttpInfo(text);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Sentiment analysis score using a model trained for buy signals. Gives a 0 to 1 score, depending on buy/sell sentiment
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> SentimentGetPriceSentimentAsyncWithHttpInfo (Text1 text)
        {
            // verify the required parameter 'text' is set
            if (text == null)
                throw new ApiException(400, "Missing required parameter 'text' when calling SentimentAnalysisApi->SentimentGetPriceSentiment");

            var localVarPath = "/get_buy_sentiment";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (text != null && text.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(text); // http body (model) parameter
            }
            else
            {
                localVarPostBody = text; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SentimentGetPriceSentiment", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Sentiment analysis for any given blob of text Gives a -1 to 1 score, depending on bearish/bullish sentiment
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>string</returns>
        public string SentimentGetSentiment (Text text)
        {
             ApiResponse<string> localVarResponse = SentimentGetSentimentWithHttpInfo(text);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Sentiment analysis for any given blob of text Gives a -1 to 1 score, depending on bearish/bullish sentiment
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > SentimentGetSentimentWithHttpInfo (Text text)
        {
            // verify the required parameter 'text' is set
            if (text == null)
                throw new ApiException(400, "Missing required parameter 'text' when calling SentimentAnalysisApi->SentimentGetSentiment");

            var localVarPath = "/get_sentiment";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (text != null && text.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(text); // http body (model) parameter
            }
            else
            {
                localVarPostBody = text; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SentimentGetSentiment", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Sentiment analysis for any given blob of text Gives a -1 to 1 score, depending on bearish/bullish sentiment
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> SentimentGetSentimentAsync (Text text)
        {
             ApiResponse<string> localVarResponse = await SentimentGetSentimentAsyncWithHttpInfo(text);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Sentiment analysis for any given blob of text Gives a -1 to 1 score, depending on bearish/bullish sentiment
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">String of text to be analyzed. I can be in any language.</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> SentimentGetSentimentAsyncWithHttpInfo (Text text)
        {
            // verify the required parameter 'text' is set
            if (text == null)
                throw new ApiException(400, "Missing required parameter 'text' when calling SentimentAnalysisApi->SentimentGetSentiment");

            var localVarPath = "/get_sentiment";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (text != null && text.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(text); // http body (model) parameter
            }
            else
            {
                localVarPostBody = text; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SentimentGetSentiment", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

    }
}
